---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/fluxcd/helm-operator//deploy?ref=v1.2.0
patches:
  - target:
      kind: Deployment
      name: helm-operator
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value:
          - --enabled-helm-versions=v3
