---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  releaseName: jenkins
  chart:
    repository: https://charts.jenkins.io
    name: jenkins
    version: '2.19.0'
  valuesFrom:
    - configMapKeyRef:
        name: jenkins-values
        namespace: jenkins