pipeline {
  agent any
  options { timestamps() }
  stages {
    stage('echo') {
      steps {
        script {
          def user = currentBuild.getBuildCauses('hudson.model.Cause$UserIdCause')[0].get('userName')
          echo "hello $user"
        }
      }
    }
  }
}